//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demowebthi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanHangQuanAoEntities : DbContext
    {
        public QLBanHangQuanAoEntities()
            : base("name=QLBanHangQuanAoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhChiTietSP> AnhChiTietSP { get; set; }
        public virtual DbSet<ChiTietDH> ChiTietDH { get; set; }
        public virtual DbSet<ChiTietSPBan> ChiTietSPBan { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<MauSac> MauSac { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<PhanLoai> PhanLoai { get; set; }
        public virtual DbSet<PhanLoaiPhu> PhanLoaiPhu { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<SPtheoMau> SPtheoMau { get; set; }
    }
}
