//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Web;
using System;

namespace demowebthi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMau = new HashSet<SPtheoMau>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaPhanLoai { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá trị")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Vui lòng chỉ nhập số")]
        public Nullable<long> GiaNhap { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá trị")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Vui lòng chỉ nhập số")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá trị")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Vui lòng chỉ nhập số")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MoTaNgan { get; set; }
        public string AnhDaiDien { get; set; }
    
        [DataType(DataType.Upload)]
        [ImageFileValidation(ErrorMessage = "Vui lòng chọn một tệp ảnh có đuôi là .jpg")]
        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public string MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMau { get; set; }
    }
}
public class ImageFileValidationAttribute : ValidationAttribute
{
    public override bool IsValid(object value)
    {
        if (value is HttpPostedFileBase file)
        {
            string extension = Path.GetExtension(file.FileName);
            return extension.Equals(".jpg", StringComparison.OrdinalIgnoreCase);
        }

        // Return true if the value is null, as we have a Required attribute as well.
        return true;
    }
}